---
- name: Provision Terraform Backend Infrastructure on AWS
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.aws
    - amazon.aws

  roles:
    - terraform-s3-backend

