#SPDX-License-Identifier: MIT-0
---
# vars file for terraform-s3-backend

region: us-east-1
s3_bucket_name: tee-state-newtenbucket
dynamodb_table_name: terraform-lockable-table
read_capacity: 5
write_capacity: 5
hash_key: LockID
hash_key_type: STRING
resource_tags:
  Environment: dev
  Owner: ansible

