---
- name: Create S3 bucket for Terraform state
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket_name }}"
    state: present
    region: "{{ region }}"
    versioning: true
      #   status: Enabled
    tags: "{{ resource_tags }}"

- name: Create DynamoDB table
  community.aws.dynamodb_table:
    name: "{{ dynamodb_table_name }}"
    region: "{{ region }}"
    hash_key_name: "{{ hash_key }}"
    hash_key_type: "{{ hash_key_type }}"
    read_capacity: "{{ read_capacity }}"
    write_capacity: "{{ write_capacity }}"
    tags: "{{ resource_tags }}"
    state: present
  register: dynamodb_result

- name: Print result
  debug:
    var: dynamodb_result
      
- name: Render Terraform backend config
  template:
    src: backend.tf.j2
    dest: "{{ terraform_dir }}/backend.tf"


